services:
  - type: web
    name: alphaedge-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: mysecretkey
      - key: FRONTEND_ORIGIN
        value: https://mrdevashish.github.io/alphaedge
