services:
  - type: web
    name: alphaedge-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: mysecretkey
      - key: FRONTEND_ORIGIN
        value: https://mrdevashish.github.io
